const routes = {
  dashboard: '/',
  hospital: '/hospital',
  news: '/news',
  category: '/categorynews',
  user: '/user',
  doctor: '/doctor',
  systemAdmin: '/system-admin',
  contactCooperate: '/contact-cooperate',
  form: '/form',
  bar: '/bar',
  pie: '/pie',
  line: '/line',
  faq: '/faq',
  calendar: '/calendar',
  geography: '/geography',
  login: '/login',
  unauthorized: '/unauthorized',
  schedulerDoctor: '/scheduler-doctor',
  schedulerAppointment: '/scheduler-appointment',
  AdminProfile: '/profile',
};
export default routes;
